name: bilibili-task


on:
  
  #push: # push触发
    #branches: [ main ]
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: 30 05 09 * ? # cron表达式，Actions时区是UTC时间，所以要往前推8个小时,如上表示每天13点10分
    

jobs:
  bilibili-task:
    if: github.event.repository.owner.id == github.event.sender.id

    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12]
        node-registry: ['https://registry.npmjs.org']

    steps:
    
    # 检出
    - name: Checkout
      uses: actions/checkout@v2
      
    # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: ${{ matrix.node-registry }}

    # 安装依赖
    - name: Install dependencies
      run: npm install
       
    
    # 运行 bilibili 签到任务
    - name: Run bilibili daily task
      env:
        DedeUserID: ${{secrets.bilibili_USERID}}
        SESSDATA: ${{secrets.bilibili_SESSDATA}}
        bili_jct: ${{secrets.bilibili_BILIJCT}}
        otherConfigs: ${{secrets.bilibili_OTHERCONFIGS}}
      run: node index.js bilibili --DedeUserID=${DedeUserID} --SESSDATA=${SESSDATA} --bili_jct=${bili_jct} ${otherConfigs}
